site_name: Swamp Dragon
pages:
- [index.md, Home]
- [quick-start.md, Quickstart]
- [routers.md, Routers]
- [serializers.md, Serializers]
- [pagination.md, Pagination]
- [sessions.md, Sessions]
- [file-upload.md, File upload]
theme: united